// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetingApi.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20260130175617_exchangesnosavingspocket")]
    partial class exchangesnosavingspocket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoBudget_Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Accommodation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Exchanges"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Income"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pockets"
                        });
                });

            modelBuilder.Entity("AutoBudget_Backend.Models.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Keyword = "TESCO"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Keyword = "ASDA"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Keyword = "LIDL"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Keyword = "ALDI"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Keyword = "SAINSBURY'S"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Keyword = "SUPERVALU"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Keyword = "DUNNES STORES"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Keyword = "CO-OP"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Keyword = "CENTRA"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Keyword = "ASDA"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Keyword = "FITNESS"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Keyword = "GYM"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Keyword = "AMAZON"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Keyword = "RENT"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Keyword = "VODAFONE"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Keyword = "EIR"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Keyword = "TESCOMOBILE"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Keyword = "THREE"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Keyword = "VIRGINMEDIA"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            Keyword = "HOTEL"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Keyword = "HOSTEL"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            Keyword = "BUS"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            Keyword = "TRANSLINK"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            Keyword = "RYANAIR"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Keyword = "FERRY"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Keyword = "UBER"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            Keyword = "EXCHANGED"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            Keyword = "PAYMENT"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 9,
                            Keyword = "TRANSFER FROM"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 10,
                            Keyword = "TRANSFER TO"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 12,
                            Keyword = "POCKET"
                        });
                });

            modelBuilder.Entity("AutoBudget_Backend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AutoBudget_Backend.Models.CategoryRule", b =>
                {
                    b.HasOne("AutoBudget_Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoBudget_Backend.Models.Transaction", b =>
                {
                    b.HasOne("AutoBudget_Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
